name: kavach_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^10.4.6
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  flutter_gen: ^5.4.0
  fluttertoast: ^8.2.4
  firebase_core: ^2.25.4
  motion_toast: ^2.8.0
  mailer: ^6.1.0
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_otp_text_field: ^1.1.1
  email_validator: ^2.1.17
  flutter_svg: ^2.0.9
  go_router: ^13.2.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  device_info: ^2.0.0
  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  flutter_tts: ^3.8.5
  url_launcher: ^6.2.1
  permission_handler: ^11.3.0
  fast_contacts: ^3.1.3
  contacts_service: ^0.6.3
  intl: ^0.18.0
  pin_code_text_field: ^1.8.0
  flutter_localization: ^0.2.0
  geolocator: ^8.0.4
  geocoding: ^2.2.1
  flutter_datetime_picker: ^1.5.1
  google_maps_flutter_android: ^2.1.10
  firebase_messaging: ^14.7.17
  youtube_player_flutter: ^9.0.0
  speech_to_text: ^6.1.0
  uuid: ^3.0.5
  direct_sms: ^0.0.1
  flutter_background_service: ^5.0.5
  shake: ^2.2.0
  flutter_background: ^1.0.6
  audioplayers: ^5.2.1
  flutter_sound: ^8.0.0+2
  just_audio: ^0.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_dynamic_links: ^5.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - json_file/
    - assets/images/
  fonts:
    - family: Kalam
      fonts:
        - asset: assets/fonts/KalamRegular.ttf
          weight: 400
    - family: Cabin
      fonts:
        - asset: assets/fonts/CabinRegular.ttf
          weight: 400
    - family: Arial
      fonts:
        - asset: assets/fonts/ArialMT.ttf
          weight: 400
        - asset: assets/fonts/ArialBoldMT.ttf
          weight: 700

